apiVersion: batch/v1
kind: CronJob
metadata:
  name: make-db-cronjob
spec:
  schedule: "0 0 * * *" # Runs every day at midnight UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: make-db-app
            image: asia-south2-docker.pkg.dev/able-folio-466619-j4/stock-cast-repo/make-db:1.0.0
            imagePullPolicy: Always
            env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "stock_cast"
            - name: DB_NAME
              value: "stock_cast"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: DB_PASSWORD
            - name: BD_STOCK_API_URL
              value: "http://bd-stock-api-service"
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
            args:
              - "--structured-logs"
              - "--credentials-file=/secrets/key.json"
              - "able-folio-466619-j4:asia-south2:stock-cast"
            securityContext:
              runAsNonRoot: true
            volumeMounts:
            - name: gcp-sa-key-volume
              mountPath: /secrets
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: gcp-sa-key-volume
            secret:
              secretName: gcp-sa-key
