apiVersion: v1
kind: Secret
metadata:
  name: backend-credentials
stringData:
  DB_PASSWORD: "}62Zn**y|{^UKZ3~"
  JWT_SECRET: "s6Ndh+pW4cTw7Y0kX8Z3v39mdj39rfnn"
  SMTP_PASSWORD: "ogpq elxx ofpu asmg"
