
name: BD Stock API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'bd-stock-api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'bd-stock-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bd-stock-api

    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
